### ***Deep Learning Fundamentals | Day 67 📊***
***
- ***Perceptron Implementation (Single Neural Network)***

In [1]:
import torch
import torch.nn as nn

In [7]:
## Input
torch.manual_seed(42)

inputs = torch.tensor([1.0,2.0,3.0])
neuron = nn.Linear(in_features=3,out_features=1)
output = neuron(inputs)

In [8]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [9]:
## Verify ... formula
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [10]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [11]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)