### NumPy Assignment Solution

In [2]:
import numpy as np

In [5]:
## Ques_1
arr = np.random.randint(1,21,size=(5,5))
print(f"Original Array: {arr}")

arr[:,2] = 1
print(f"Modified Array:{arr}")


Original Array: [[ 8  1 18 13 20]
 [15 15 14  7  8]
 [ 5  9 18 11 10]
 [10  6 13  7  2]
 [14 15 15  5 15]]
Modified Array:[[ 8  1  1 13 20]
 [15 15  1  7  8]
 [ 5  9  1 11 10]
 [10  6  1  7  2]
 [14 15  1  5 15]]


In [7]:
## Ques_2
arr = np.arange(1,17).reshape((4,4))
print(f"Original Array:{arr}")

np.fill_diagonal(arr,0)
print(f"Modified Array:{arr}")

Original Array:[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array:[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [9]:
## Ques_3
arr = np.arange(1,37).reshape((6,6))
print(f"Original Array:{arr}")

sub_arr = arr[2:5,1:4]
print(f"SubArray:{sub_arr}")

Original Array:[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
SubArray:[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [11]:
arr = np.random.randint(1,21,size=(5,5))
print(f"Original Array:{arr}")

border_el = np.concatenate((arr[0,:],arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]))
print(f"Border Element:{border_el}")

Original Array:[[ 3 11 10 17  7]
 [11 20  3  4 11]
 [10  2 16 19 19]
 [20 17  3  3  2]
 [17 17 12 13 16]]
Border Element:[ 3 11 10 17  7 17 17 12 13 16 11 10 20 11 19  2]


In [12]:
## Ques_5

array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)


Array 1:
[[ 2  4  4  8]
 [ 3  1  1  5]
 [ 2  2 10  1]]
Array 2:
[[7 6 9 9]
 [5 8 1 9]
 [8 7 3 3]]
Element-wise addition:
[[ 9 10 13 17]
 [ 8  9  2 14]
 [10  9 13  4]]
Element-wise subtraction:
[[-5 -2 -5 -1]
 [-2 -7  0 -4]
 [-6 -5  7 -2]]
Element-wise multiplication:
[[14 24 36 72]
 [15  8  1 45]
 [16 14 30  3]]
Element-wise division:
[[0.28571429 0.66666667 0.44444444 0.88888889]
 [0.6        0.125      1.         0.55555556]
 [0.25       0.28571429 3.33333333 0.33333333]]
