### Common Data Types in Numpy
- Integers: int32, int64
- Floating point nums: float32, float64
- Boolean: bool
- Complex nums: complex64, complex128
- String: S (byte-str) & U (unicode-str)
- Object: generic python objects - object

In [2]:
import numpy as np

In [4]:
## Common Datatype
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([1.0,2.0,5.0,7.0])
ar3 = np.array(["Python","DS","AIML"])

print(ar1.dtype)
print(ar2.dtype)
print(ar3.dtype)
print(ar1.nbytes)

int64
float64
<U6
40


In [6]:
new_arr = ar1.astype("float64")
print(new_arr,new_arr.dtype)

[1. 2. 3. 4. 5.] float64


In [7]:
arr = np.array([1,2,3,4,5],dtype="float64")
print(arr,arr.dtype)

[1. 2. 3. 4. 5.] float64


In [8]:
##  Complex Numbers
arr1 = np.array([2 + 3j])
arr2 = np.array([5 + 8j])
print(arr1, arr1.dtype)

[2.+3.j] complex128


In [9]:
print(arr1+arr2)
print(arr1-arr2)

[7.+11.j]
[-3.-5.j]


In [10]:
## Objects 
arr = np.array(["hello",{1,2,3},3.14])
print(arr,arr.dtype)

['hello' {1, 2, 3} 3.14] object


***
### Vectorization & Broadcasting

**Vectorization**: It is the process of applying operations to entire arrays or sequences of data at once, rather than iterating through individual elements using explicit loops. 

**Broadcasting**: It is a mechanism that allows NumPy to perform operations on arrays of different shapes without explicitly reshaping them (creating copies of the smaller array to match the larger array's shape). 

- Broadcasting Condition
   - For broadcasting to happen the dimensions should be compatible. 
   - Numpy compares shape element-wise. It starts dimension comparison with the trailing (i.e. rightmost) dimension and works its way left. 
   - Two dimensions are compatible when <ol> <li>they are equal, or</li> <li>one of them is 1. </li>

In [11]:
## Vectorization
arr = np.array([1, 2, 3, 4, 5])

sq_arr = arr ** 2       
print(sq_arr)

arr2 = np.array([6, 7, 8, 9, 10])
print(arr + arr2)      

#Broadcasting
arr_mul10 = arr * 10  
print(arr_mul10)

arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1D + arr2D)

[ 1  4  9 16 25]
[ 7  9 11 13 15]
[10 20 30 40 50]
[[2 4 6]
 [5 7 9]]


In [13]:
## Vector Normalization
arr = np.array([[1,2,3],[4,5,7]])
mean = np.mean(arr)
std_dv = np.std(arr)

print((arr-mean)/std_dv)

[[-1.35224681 -0.84515425 -0.3380617 ]
 [ 0.16903085  0.6761234   1.69030851]]


In [14]:
## column wise
arr = np.array([[1, 2], [3, 4], [5, 6]])
mean = np.mean(arr, axis = 0)
std_dev = np.std(arr, axis = 0)
print((arr-mean) / std_dev)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


***

### Mathematical Functions in NumPy
- Aggregation functions
   - sum()
   - prod()
   - min() & argmin() : min val & idx of min val
   - max() & argmax() : max val & idx of max val
   - mean()
   - median()
   - std() - standard deviation
   - var() - variance

In [15]:
## Mathematical Functions
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))     
print(np.prod(arr))    
print(np.min(arr))    
print(np.argmin(arr))  
print(np.max(arr))     
print(np.argmax(arr))  
print(np.mean(arr))    
print(np.median(arr))  
print(np.std(arr))     
print(np.var(arr))   

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0


- Power Functions
  - squre( )
  - sqrt( )
  - pow(a,b)

In [20]:
arr = np.array([1,2,3,4,5,7])
print(np.square(arr))   
print(np.sqrt(arr))     
print(np.pow(arr, 3))

[ 1  4  9 16 25 49]
[1.         1.41421356 1.73205081 2.         2.23606798 2.64575131]
[  1   8  27  64 125 343]


- Log & Exponential functions
   - log( ) - natual log
   - log10( ) - log base 10
   - log2( ) - log base 2
   - exp( ) - exponentional i.e. e^x

In [17]:
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.94591015]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.84509804]
[0.         1.         1.5849625  2.         2.32192809 2.80735492]
[   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591
 1096.63315843]


- Rounding functions
   - round( ) - rounds to nearest value
   - floor( ) - rounds down
   - ceil( ) - rounds up
   - trunc( ) - truncates decimal part

In [18]:
print(np.round(2.678))    
print(np.floor(2.678))    
print(np.ceil(2.678))     
print(np.trunc(2.678))

3.0
2.0
3.0
2.0


- Additional functions
   - abs() - absolute value
   - sort() - sort all values (asc or desc)
   - unique() - returns unique values

In [19]:
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5])

print(np.abs(arr))     
print(np.sort(arr))  
print(np.unique(arr))  

[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]
