### Day_8 of AIML Journey { NumPy }

- NumPy(Numerical Python): It is an open source library used for numerical computing.
- Features  
    - Multidimensional Arrays
    - Mathematical Functions
    - Vectorization
    - Interoperability

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


- Python List vs NumPy Arrays

In [ ]:
import numpy as np
import time

## execution time comparision
size = 10_000_000  # 10M Dataset
Python_list = list(range(size))
st = time.time()
lst_sq = [x**2 for x in Python_list]
ed = time.time()
print(f"Python List Execution Time:{ed-st} seconds ")

## Numpy Arrays (much faster)
numpy_arr = np.array(Python_list)
st = time.time()
arr_sq = numpy_arr ** 2 # vector operation
ed = time.time()
print(f"Numpy Array Execution Time:{ed-st} seconds")

Python List Execution Time:1.068835973739624 seconds 
Numpy Array Execution Time:0.025754690170288086 seconds


In [4]:
## Memory Usage Comparison
import sys
print(f"Python List Size:{sys.getsizeof(Python_list)*len(Python_list)}")
print(f"Numpy Array Size:{numpy_arr.nbytes}")

Python List Size:800000560000000
Numpy Array Size:80000000


In [5]:
## Numpy arrays creation from (list)
arr = np.array([1,2,3,4,5,"AIML"])
print(arr,type(arr))

['1' '2' '3' '4' '5' 'AIML'] <class 'numpy.ndarray'>


In [6]:
## 2D Matrix
arr = np.array([[1,2,3,4,5],[7,8,9,10,12]])
print(arr,arr.shape)

[[ 1  2  3  4  5]
 [ 7  8  9 10 12]] (2, 5)


In [7]:
## 3D Matrix
arr = np.array([[1,2,3,4,5],[7,8,9,10,12],[2,3,4,5,7]])
print(arr,arr.shape)

[[ 1  2  3  4  5]
 [ 7  8  9 10 12]
 [ 2  3  4  5  7]] (3, 5)


In [8]:
## Numpy Array Inbuilt Functions
arr = np.zeros((3,3))
print(arr,arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (3, 3)


In [9]:
arr =np.ones((2,2))
print(arr,arr.shape)

[[1. 1.]
 [1. 1.]] (2, 2)


In [10]:
arr = np.full((3,3),5)
print(arr,arr.shape)

[[5 5 5]
 [5 5 5]
 [5 5 5]] (3, 3)


In [12]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
## Important for generating sequence of numbers.
arr = np.arange(1,20,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
arr = np.linspace(0,10,5) # evenly spaced array
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [18]:
## Arrays Properties
arr = np.array([[1,2,3],
               [3,4,5],[7,8,9]])

print(arr.shape) # dimensions - (m x n)
print(arr.size) # total elements - m*n
print(arr.ndim) # dimension
print(arr.dtype) # data type object

(3, 3)
9
2
int64


In [22]:
## Changing Datatype
str_arr = np.array([1,2,3],dtype="U")
print(str_arr,str_arr.dtype)

float_arr = np.array([1,2,3],dtype="float64")
print(float_arr,float_arr.dtype)

int_arr = float_arr.astype(np.int64)
print(int_arr,int_arr.dtype)

['1' '2' '3'] <U1
[1. 2. 3.] float64
[1 2 3] int64


- Operations on Numpy

In [27]:
## Reshaping
arr = np.array([1,2,3,4,5,7])
print(arr.shape)

reshaped = arr.reshape((2,3))
print(reshaped,reshaped.shape)

## convert 2D -> 1D
flatten = reshaped.flatten()
print(flatten,flatten.shape)

(6,)
[[1 2 3]
 [4 5 7]] (2, 3)
[1 2 3 4 5 7] (6,)


In [29]:
## Indexing
arr = np.array([1,2,3,4,5,7])
print(arr[2])
print(arr[0])

3
1


In [31]:
## 2D Aray Indexing
arr = np.array([[1,2,3],[4,5,7],[2,8,9]])
print(arr[0][1])
print(arr[1][2])

2
7


In [32]:
## Fancy Indexing
arr = np.array([1,2,3,4,5,7])
idx = [0,2,4]
print(arr[idx])

[1 3 5]


In [34]:
## Boolean Indexing
print(arr[arr > 2])
print(arr[arr%2 == 0])

[3 4 5 7]
[2 4]


In [35]:
## Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:6]) 
print(arr[:6]) 
print(arr[3:])
print(arr[::2])

[3 4 5 6]
[1 2 3 4 5 6]
[4 5 6 7]
[1 3 5 7]


#### Copy v/s View  
- Slicing a list returns a copy but slicing a NumPy array returns a view(changes in original data).
   - Views are fast and memory-efficient (no data duplication). 
   - Copies are safe but slower and use more memory

In [36]:
## sliced list is a copy
py_list = [1, 2, 3, 4, 5]
copy_list = py_list[1:4]
copy_list[1] = 333

print(copy_list)
print(py_list)

[2, 333, 4]
[1, 2, 3, 4, 5]


In [40]:
## sliced numpy array is a view
np_arr = np.array([1, 2, 3, 4, 5])
view_arr = np_arr[1:4]
view_arr[1] = 333

print(view_arr)
print(np_arr)

[  2 333   4]
[  1   2 333   4   5]


In [41]:
## Creating Copy
copy_arr = np_arr[1:5]
copy_arr[2] = 34
print(copy_arr)
print(np_arr)

[  2 333  34   5]
[  1   2 333  34   5]


- Operation Along Axis

In [42]:
arr = np.array([[1,3,2],[4,5,7],[8,9,10]])
print(arr)
print(np.sum(arr)) # entire arr sum

[[ 1  3  2]
 [ 4  5  7]
 [ 8  9 10]]
49


In [43]:
column_sum = np.sum(arr,axis=0)
print(column_sum) # sum along column

[13 17 19]


In [44]:
row_sum = np.sum(arr,axis=1)
print(row_sum)

[ 6 16 27]


In [46]:
## slicing
print(arr[0:3,1:3])

[[ 3  2]
 [ 5  7]
 [ 9 10]]


In [47]:
## 3D Array Operation
arr = np.array([[[1,2,3],[4,5,7],[8,9,10]],[[1,2,3],[4,5,7],[8,9,10]]])

print(arr)
print(arr.shape)

[[[ 1  2  3]
  [ 4  5  7]
  [ 8  9 10]]

 [[ 1  2  3]
  [ 4  5  7]
  [ 8  9 10]]]
(2, 3, 3)


In [48]:
## Indexing
print(arr[0][1][1])   
print(arr[1][2][1]) 

5
9


In [49]:
print(arr[:, :, 0]) # first col from both layers
print(arr[:, 0, :]) # first row from both layers

[[1 4 8]
 [1 4 8]]
[[1 2 3]
 [1 2 3]]


In [50]:
## Manipulation Data
arr[:,0,:] = 12 # change first row
print(arr)

[[[12 12 12]
  [ 4  5  7]
  [ 8  9 10]]

 [[12 12 12]
  [ 4  5  7]
  [ 8  9 10]]]


In [51]:
arr[:,:,0] = 7 # change first column
print(arr)

[[[ 7 12 12]
  [ 7  5  7]
  [ 7  9 10]]

 [[ 7 12 12]
  [ 7  5  7]
  [ 7  9 10]]]
